---
title: "Tarea 3"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulea
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes, warning=FALSE, message=FALSE}
library(dplyr)
library(sf)
library(terra)
library(raster)
library(rgdal)
library(DT)
library(plotly)
library(leaflet)
library(leafem)
library(leaflet.extras)
library(shiny)
```


```{r datos, warning=FALSE, message=FALSE}
# Lectura de una capa vectorial (GeoJSON) de división distrial de Santa Ana
limite_distrital <-
  st_read(
    "https://dvictoria2020.github.io/Proyecto1-R/limite_distrital.geojson",
    quiet = TRUE
  )
# Transformación del CRS del objeto división distrital
limite_distrital <-
  limite_distrital %>%
  st_transform(4326)
# Lectura de archivo CSV de patentes comerciales en Santa Ana
Patente_final <-
  st_read(
    "/vsicurl/https://dvictoria2020.github.io/Proyecto1-R/Patente_final.csv",
    options = c(
      "X_POSSIBLE_NAMES=Latitud",
      "Y_POSSIBLE_NAMES=Longitud"
    ),
    quiet = TRUE
  )
# Asignación de un CRS al objeto patentes
st_crs(Patente_final) <- 4326
# Lectura de capa raster de uso urbano
uso_urbano_rWGS <-
  rast(
    "/vsicurl/https://dvictoria2020.github.io/Proyecto1-R/uso_urbano_rWGS.tif",
  )

# Lista ordenada de distritos + "Todos"
lista_distritos <- unique(Patente_final$Distrito)
lista_distritos <- sort(lista_distritos)
lista_distritos <- c("Todos", lista_distritos)

# Lista ordenada de actividad de patentes + "Todas"
lista_patentes <- unique(Patente_final$Actividad)
lista_patentes <- sort(lista_patentes)
lista_patentes <- c("Todas", lista_patentes)
```

Column {.sidebar}
-----------------------------------------------------------------------



```{r filtros}
# Selector de distrito
ui <- dashboardPage(
 dashboardHeader(title = "Patentes Santa Ana"),
 dashboardSidebar(sidebarMenu(
 menuItem(
 text = "Filtros",
selectInput(
  inputId = "distrito",
  label = "Distrito",
  choices = lista_distritos,
  selected = "Todos"
),
# Selector de actividad comercial
selectInput(
  inputId = "actividad",
  label = "Actividad comercial",
  choices = lista_patentes,
  selected = "Todas"
),
# Selector de fecha de aprobación
dateRangeInput(
  inputId = "fecha",
  label = "Fecha de aprobación",
  start = "1991-01-01",
  end   = Sys.Date(),
  separator = " a ",
  language = "es"
),
startExpanded = TRUE
 )
 )),
 dashboardBody(fluidRow(
 box(
 title = "Mapa de ubicación de patentes comerciales",
 leafletOutput(outputId = "mapa"),
 width = 8
 ),
 box(
 title = "Distribución...",
 plotOutput(outputId = "grafico"),
 width = 4
 ),
 fluidRow(
 box(
 title = "Registros de actividad",
 DTOutput(outputId = "tabla"),
 width = 12
 ) 
 ) 
 ))
)
# Función para filtrar registros con base en los controles de entrada
server <- function(input, output, session) {
 filtrarRegistros <- reactive ({
  actividad_filtrada <-
    Patente_final %>%
    dplyr::select(Nombre_comercio, Aprobacion, Actividad, Tipo_persona, Distrito)
  
  
  # Filtrado de actividad por distrito
  if (input$distrito != "Todas") {
    actividad_filtrada <-
      actividad_filtrada %>%
      filter(distrito == input$distrito)
  } 
  # Filtrado de actividad por fecha
  actividad_filtrada <-
    actividad_filtrada %>%
    filter(
      Aprobacion >= as.Date(input$fecha[1], origin = "1985-01-01") &
        Aprobacion <= as.Date(input$fecha[2], origin = "1985-01-01")
    )
    # Filtrado de actividad por tipo de personería
  if (input$Persona != "Todas") {
    actividad_filtrada <-
      actividad_filtrada %>%
      filter(Tipo_persona == input$Persona)
  }
  return (actividad_filtrada)
})
```

Row {data-height=550}
-----------------------------------------------------------------------

### Muestra de distribución de patentes comerciales en Santa Ana

```{r mapa, warning=FALSE}
 output$mapa <- renderLeaflet ({
 registros <- filtrarRegistros()
  
# Conversión del objeto uso a la clase RasterLayer
uso_urbano_rWGS_rl <- raster::raster(uso_urbano_rWGS)

# Mapa leaflet
leaflet() %>%
  addTiles(options = providerTileOptions(noWrap = TRUE), group="Open Street Maps") %>%
  addProviderTiles("Esri.WorldImagery", group="Imagen Satelital")%>%
  addRasterImage(
    uso_urbano_rWGS_rl,
    color= "#DDB892",
    opacity = 0.6,
    group = "Uso Urbano 2005"
  ) %>%
  addPolygons(
    data = limite_distrital,
    color = "purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 2.0,
    group = "Limite distrital"
  ) %>% 
  addCircleMarkers(
    data = registros,
    stroke = TRUE,
    radius = 4,
    fillColor = 'orange',
    fillOpacity = 1,
    label = paste0(
      registros$Actividad,
       ", ",
      registros$Distrito,
       ", ",
      registros$Aprobacion,
    ),
    popup = paste0(
        "<strong>Distrito: </strong>",
        "<em>",
        registros$Distrito,
        "</em>",
        "<br>",
        "<strong>Actividad Comercial: </strong>",
        registros$Actividad,
      ),
    clusterOptions = markerClusterOptions(),
    group = "Patentes comerciales"
    )

    addMiniMap(
    tiles = providers$OpenStreetMap,
    toggleDisplay = TRUE
  ) %>%
 
   addLayersControl(
   baseGroups = c("Open Street Maps","Imagen Satelital"),
   overlayGroups = c("Uso Urbano 2005","Limite distrital", "Patentes comerciales"), 
   options = layersControlOptions(collapsed = FALSE)
  )
    addSearchOSM() %>%
    addResetMapButton() %>%
    addMouseCoordinates()
    addScaleBar("bottomright") %>%
    addResetMapButton() %>%
    addFullscreenControl() %>%
    addControlGPS()
    
})

```

Row {data-height=350}
-----------------------------------------------------------------------


### Gráfico 1

```{r cantidad}
tipo_persona_distrito <-
  Patente_final %>%
  dplyr::count(Tipo_persona, Distrito)
```

```{r grafico-barras-apiladas}
  ggplot() + geom_col(
      data= tipo_persona_distrito,
      aes(x= Distrito,
          y= n, fill = Tipo_persona), width = 0.7)+
  
      ggtitle( "Distribución de patentes comerciales por tipo de personería
                          en los distritos de Santa Ana") +
      xlab("Distrito") + 
      ylab("Total de patentes") +
      scale_fill_manual(values = c("#FFE4C4", "#8B7D6B")) +
      theme (
        legend.title = element_blank(),
        legend.position = "right",
        plot.title = element_text(size = 14, face = "plain")
        
  )
```

Row
-----------------------------------------------------------------------

```{r tabla}
  licenciascomerciales %>%
  st_drop_geometry()
  datatable()
  })

shinyApp(ui, server)
  
```




